{% set version = '1.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bcrocsurface
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bcROCsurface_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bcROCsurface/bcROCsurface_{{ version }}.tar.gz
  sha256: d44a1b2f456508d10d901e662cb4813f517cc89682e6e179c131dc6b972234bd

build:
  merge_build_host: True  # [win]
  number: 0
  # no r-rgl package for macOS
  skip: true  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-rcpp >=0.12.2
    - r-rcpparmadillo
    - r-boot
    - r-nnet
    - r-rgl
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.2
    - r-rcpparmadillo
    - r-boot
    - r-nnet
    - r-rgl

test:
  commands:
    - $R -e "library('bcROCsurface')"           # [not win]
    - "\"%R%\" -e \"library('bcROCsurface')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bcROCsurface
  license: GPL (>= 2)
  summary: The bias-corrected estimation methods for the receiver operating characteristics ROC
    surface and the volume under ROC surfaces (VUS) under missing at random (MAR) assumption.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
