{% set version = '1.0-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-bcrocsurface
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/bcROCsurface_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/bcROCsurface/bcROCsurface_{{ version }}.tar.gz
  sha256: d44a1b2f456508d10d901e662cb4813f517cc89682e6e179c131dc6b972234bd

build:
  merge_build_host: True  # [win]
  number: 1
  # no r-rgl package for macOS
  skip: true  # [osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxfixes') }}         # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - r-base
    - r-rcpp >=0.12.2
    - r-rcpparmadillo
    - r-boot
    - r-nnet
    - r-rgl
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.2
    - r-rcpparmadillo
    - r-boot
    - r-nnet
    - r-rgl

test:
  commands:
    - LD_LIBRARY_PATH=${BUILD_PREFIX}/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib64 $R -e "library('bcROCsurface')"  # [not win]
    - "\"%R%\" -e \"library('bcROCsurface')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=bcROCsurface
  license: GPL (>= 2)
  summary: The bias-corrected estimation methods for the receiver operating characteristics ROC
    surface and the volume under ROC surfaces (VUS) under missing at random (MAR) assumption.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: bcROCsurface
# Version: 1.0-3
# Date: 2018-10-16
# Title: Bias-Corrected Methods for Estimating the ROC Surface of Continuous Diagnostic Tests
# Author: Khanh To Duc, with contributions from Monica Chiogna and Gianfranco Adimari
# Maintainer: Khanh To Duc <toduc@stat.unipd.it>
# Description: The bias-corrected estimation methods for the receiver operating characteristics ROC surface and the volume under ROC surfaces (VUS) under missing at random (MAR) assumption.
# License: GPL (>= 2)
# Depends: R(>= 2.15.0), nnet, rgl, boot, stats, utils, graphics, parallel
# Imports: Rcpp (>= 0.12.2)
# LinkingTo: Rcpp, RcppArmadillo
# LazyLoad: yes
# LazyData: TRUE
# ByteCompile: yes
# Encoding: UTF-8
# RoxygenNote: 6.1.0
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2018-10-16 15:00:01 UTC; khanh
# Repository: CRAN
# Date/Publication: 2018-10-16 18:30:06 UTC
